# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:53
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootCrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FileField(upload_to='root')),
                ('crt', models.FileField(upload_to='root')),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=256)),
                ('organizational_unit_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FileField(upload_to=core.models.directory_path)),
                ('crt', models.FileField(upload_to=core.models.directory_path)),
                ('cn', models.CharField(max_length=256, unique=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
