# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:16
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcrt',
            name='crt_text',
            field=core.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootcrt',
            name='key_text',
            field=core.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecrt',
            name='crt_text',
            field=core.models.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecrt',
            name='key_text',
            field=core.models.EncryptedTextField(blank=True, null=True),
        ),
    ]
