# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcrt',
            name='crt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rootcrt',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='crt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='key',
            field=models.TextField(),
        ),
    ]
