# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models

from core.models import directory_path_crt, directory_path_key, directory_path_root_crt, directory_path_root_key


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_from_files_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcrt',
            name='crt',
            field=models.FileField(upload_to=directory_path_root_crt, default='test'),
        ),
        migrations.AlterField(
            model_name='rootcrt',
            name='key',
            field=models.FileField(upload_to=directory_path_root_key, default='test'),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='crt',
            field=models.FileField(upload_to=directory_path_crt, default='test'),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='key',
            field=models.FileField(upload_to=directory_path_key, default='test'),
        ),
        migrations.RemoveField(
            model_name='rootcrt',
            name='crt',
        ),
        migrations.RemoveField(
            model_name='rootcrt',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sitecrt',
            name='crt',
        ),
        migrations.RemoveField(
            model_name='sitecrt',
            name='key',
        ),
        migrations.RenameField(
            model_name='rootcrt',
            old_name='crt_text',
            new_name='crt',
        ),
        migrations.RenameField(
            model_name='rootcrt',
            old_name='key_text',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='sitecrt',
            old_name='crt_text',
            new_name='crt',
        ),
        migrations.RenameField(
            model_name='sitecrt',
            old_name='key_text',
            new_name='key',
        ),
    ]
