# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:41
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170627_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcrt',
            name='crt',
            field=core.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='rootcrt',
            name='key',
            field=core.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='crt',
            field=core.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='sitecrt',
            name='key',
            field=core.models.EncryptedTextField(),
        ),
    ]
