# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootCrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FileField(upload_to='root')),
                ('crt', models.FileField(upload_to='root')),
            ],
        ),
    ]
